[book]
authors = ["ToniXWD"]
language = "zh-CN"
src = "src"
title = "Toni-LSM-Lab"

[output.html]
git-repository-url = "https://github.com/ToniXWD/toni-lsm"
edit-url-template = "https://github.com/ToniXWD/toni-lsm/edit/lab-doc/{path}"
mathjax-support = false
additional-js = ["./src/giscus.js"]
default-theme = "navy"

# [output.html.fold]
# enable = true
# level = 0

[preprocessor.katex]

[output.html.search]
enable = true
